language: objective-c
osx_image: xcode9
xcode_project: Source/InputMask/InputMask.xcodeproj
xcode_scheme: InputMask
script: xcodebuild -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6,OS=9.3' -project Source/InputMask/InputMask.xcodeproj -scheme InputMask build test
